# Customer Churn Prediction

## Data Cleaning & Preprocessing

### Objective

The objective of this notebook is to clean the raw dataset by correcting data types, removing unnecessary features, checking for duplicate records, and preparing the data for exploratory analysis.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/raw/Bank Customer Churn Prediction.csv")

df.head()

,customer_id,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
0,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
df_clean = df.copy()

In [4]:
df_clean.dtypes

customer_id           int64
credit_score          int64
country              object
gender               object
age                   int64
tenure                int64
balance             float64
products_number       int64
credit_card           int64
active_member         int64
estimated_salary    float64
churn                 int64
dtype: object

In [5]:
df_clean.isnull().sum()

customer_id         0
credit_score        0
country             0
gender              0
age                 0
tenure              0
balance             0
products_number     0
credit_card         0
active_member       0
estimated_salary    0
churn               0
dtype: int64

In [6]:
df_clean.duplicated().sum()

0

In [7]:
df_clean.drop(columns=['customer_id'], inplace=True)

In [8]:
df_clean.head()

,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [9]:
df_clean.to_csv(
    "../data/processed/bank_customer_churn_clean.csv",
    index=False
)

## Cleaning Summary

### Completed Tasks

- Loaded the raw dataset
- Created a working copy
- Checked data types
- Checked for missing values (none)
- Checked for duplicate records (none)
- Removed identifier columns (customer_id)
- Saved the cleaned dataset for future analysis

**Notes: The dataset is now ready for exploratory data analysis.**